### ISSUE TITLE
Recent release `1.0.17` breaks ipython

### ISSUE THREAD

**Issue by sphuber** [prompt-toolkit/python-prompt-toolkit#980] opened 2019-10-03 16:19 UTC
I am running `ipython==5.8.0` on Ubuntu and with the recent release `1.0.17` breaks it:
```
$ ipython
Traceback (most recent call last):
  File "/home/sphuber/.virtualenvs/aiida_dev/bin/ipython", line 6, in <module>
    from IPython import start_ipython
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/IPython/terminal/embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 16, in <module>
    from prompt_toolkit.document import Document
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/prompt_toolkit/application/__init__.py", line 3, in <module>
    from .application import Application
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 13, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/prompt_toolkit/buffer.py", line 9, in <module>
    from .completion import Completer, Completion, CompleteEvent
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/prompt_toolkit/completion/__init__.py", line 3, in <module>
    from .base import (
  File "/home/sphuber/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/prompt_toolkit/completion/base.py", line 9, in <module>
    from prompt_toolkit.eventloop import (
ImportError: cannot import name AsyncGeneratorItem
```

**Comment by sphuber** [comment] 2019-10-03 16:35
From looking a bit around in the code, it seems that it may just be a wrong build that was pushed. In my local package downloaded from PyPI with version `1.0.17` there is the module `prompt_toolkit.completion`, however this seems to be only present in the branch compatible with python3, i.e. the `prompt-toolkit==2.*` series. Maybe you ran the build in an environment that contained the files from the wrong branch.

**Comment by mic4ael** [comment] 2019-10-03 16:56
Happened to me as well. I thought I was going crazy with my Docker builds until I realized the new version was released less than one hour ago.

**Comment by natekupp** [comment] 2019-10-03 17:30
For anyone else jumping on this, we [temporarily pinned](https://dagster.phacility.com/D1185) as:

```
'prompt-toolkit<2.0.10; python_version>="3"', 
'prompt-toolkit<1.0.17; python_version<"3"', 
```

Which resolves the issue.

**Comment by chyzzqo2** [comment] 2019-10-03 17:40
It's the wheels. they contain code from both versions. If you pull the wheels installing from the source package works fine.

**Comment by jonathanslenders** [comment] 2019-10-03 20:08
Thanks for pointing out!! I'll push a new release in a few minutes. (First trying to see where it went wrong.)

**Comment by jonathanslenders** [comment] 2019-10-03 20:22
It should be fixed now.

The issue appeared on IPython 5 only, which uses prompt_toolkit 2.0. Python 3 users were not affected because they get a more recent IPython version, which uses prompt_toolkit 2.0. (This was probably also the reason why I didn't notice it myself.)

The issue was caused by a file ``prompt_toolkit/completion.py`` in ptk2 that became a directory in ptk3. Somehow, I had some leftovers of the 2.0 branch while doing the 1.0 release.

Thanks everyone for reaching out so quickly, and sorry for the past few hours!

Jonathan

**Closed** 2019-10-10 05:34 UTC
